[package]
name = "kidex_anyrun_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyrun-plugin = "0.1.0"
kidex-common = { path = "../kidex-common", features = ["util"]}
abi_stable = "0.11.1"
fuzzy-matcher = "0.3.7"
open = "3.2.0"
serde = { version = "1.0.160", features = ["derive"] }
ron = "0.8.0"
